### PR TITLE
Limit network transfers, add `ccache`

### PR DESCRIPTION
**Pull request by sanmai-NL**
This will speed up CI builds, it's to be seen how much.

### CODE REVIEW

**Comment by kosloot** [comment]
A disadvantage might be, that underlying libraries are not rebuild.
Ucto relies on ticcutils, which is quite stable and libfolia, which is a slowly moving target.
Not caching assures that the leanest/meanest GIT versions are correct.
At the moment we don't care about speed on the Travis side.
@proycon opinions on this?

**Comment by proycon** [comment]
Interesting, I didn't know about this ``ccache`` feature of travis yet. I find it still a bit hard to judge what exactly it caches. It is indeed important that dependencies are rebuild as they change, I'm not sure if this interferes, but I suppose we could give it a try. The somewhat slow speed has never been a real issue though.

**Comment by sanmai-NL** [comment]
ccache's manual [explains](https://ccache.samba.org/manual.html#_how_ccache_works) how it guarantees that the caching will either work correctly or be disabled automatically. [An old blog post explains when it helps](https://blog.flameeyes.eu/2008/06/debunking-ccache-myths/). It would help you here since you are rebuilding some deps on every build, and it's not like they change every two CI builds of Ucto. See the [performance characteristics](https://ccache.samba.org/performance.html).

I think having the build run far quicker will mean less patience is required from casual contributors who do not build locally and who push commits to a PR branch somewhat frequently.

**Comment by proycon** [comment]
Sorry for the delay, this seems worth a try in any case yes, it probably won't hurt (and if it does we'll notice soon enough ;) )

**Pull request merged**
