### PR TITLE
Check code quality during CI

### PR DESCRIPTION
**Pull request by sanmai-NL**
With these changes, many suboptimal programming patterns will be caught before making history.

### CODE REVIEW

**Comment by proycon** [comment]
Thanks! Static analysis is indeed a good idea to add, let's see what @kosloot has to say. Currently the tests fail on it though so we'd have to solve that when merging it in.

**Comment by sanmai-NL** [comment]
I didn't address these small issues that make the build fail, to not mix up concerns. If @kosloot is okay, I can fix those too.

**Comment by sanmai-NL** [comment]
I'm now planning to add the [Clang Static Analyzer](http://clang-analyzer.llvm.org/) as well. 
[Provisional results](https://travis-ci.org/LanguageMachines/ucto/jobs/192448049).
It found a null pointer dereference in Ucto code. But apparently at least one libstdc++ header file isn't being considered a system header file (`-isystem`).
```
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/vector:62:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_construct.h:103:20: warning: Forming reference to null pointer
            std::_Destroy(std::__addressof(*__first));
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
```
I'll try to fix that later, so that `scan-build` can run with `--status-bugs` during CI builds.

**Comment by kosloot** [comment]
Static checking seems a good idea.
Playing around with scan-build a bit, I saw some false positives. So failing a build on a scan failure is unwise, I think.
But some errors did indeed lead to an improvement, which make me happy.
Didn't have time to test CPPcheck yet

**Comment by sanmai-NL** [comment]
I rebased my PR against your latest commits, and the CI build for my PR succeeds now. This uses the Clang Static Analyzer. So there are no false positives at present. I'm now running CppCheck again and fixing the remaining issues.

**Comment by sanmai-NL** [comment]
The only issues left are
```sh
[src/tokenize.cxx:710]: (style) The function 'outputTokensDoc' is never used.
[src/tokenize.cxx:194]: (style) The function 'setErrorLog' is never used.
```
The rationale behind these checks is, I think, that even library code ought to have tests that cover all functions.

**Comment by kosloot** [comment]
We indeed don't have a full testsuite with unit tests.
But 'almost' everything is checked in the tests under ./tests/
@proycon is outputTokensDoc() used in the Python wrapper? I don't have a use-case anywhere in or C++ software stack.
setErrorLog() is used by Frog.

**Comment by proycon** [comment]
Yeah, I think ``outputTokensDoc()`` is indeed used by python-ucto.

**Comment by kosloot** [comment]
I have some problems using scan-build-3.8 on our software.
This versions should support OpenMP (at last) using -fopenmp on the clang commandline.
But the scan-build fails on lines like:
#pragma omp critical (tree_mod)
@sanmai-NL Any idea how to solve this?
[clang_crash_2vD1AU.ii.stderr.txt](https://github.com/LanguageMachines/ucto/files/716092/clang_crash_2vD1AU.ii.stderr.txt)
(see attachment)

**Comment by sanmai-NL** [comment]
No idea, other than that it's definitely a bug in the Clang Static Analyzer. Perhaps related to [this one](https://llvm.org/bugs/show_bug.cgi?id=28448), since you're also returning a pointer? I remember once having a vague issue with some Clang tooling where the position of the asterisk in a type declaration actually mattered ... I'm currently setting up a containerized build env for Ucto where newer versions of deps are available. Perhaps the bug is gone with a more recent Clang version. You could try disabling the checker `alpha.security.ReturnPtrRange` in this other project in the meantime.

**Comment by kosloot** [comment]
Well, this happens with an OLDER version of Clang (3.8) and always on OpenMP stuff.
But annoying it is...

**Pull request merged**
